#!/bin/bash
set -euo pipefail

which sudo || apt-get install -y sudo
which g++ || sudo apt-get install -y build-essential

g++ -I./google-cloud-cpp -I./google-cloud-cpp/cmake-out/vcpkg_installed/x64-linux/include main.cpp
